services:
  sano:
    container_name: sano
    image: sano-music:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      PREFIX: ${PREFIX:-&}
      LANGUAGE: ${LANGUAGE:-en-US}
      DATABASE_PATH: ${DATABASE_PATH:-/app/data/data.db}
      YOUTUBE_COOKIES_PATH: ${YOUTUBE_COOKIES_PATH:-}
    volumes:
      - ${YOUTUBE_COOKIES_PATH_HOST:-/dev/null}:/app/cookies.txt:ro
      - sano-data:/app/data
    restart: on-failure
    networks:
      - sano-network

networks:
  sano-network:
    name: sano-network

volumes:
  sano-data:
